// packages/react/src/components/App.jsx
import React, { useEffect } from "react";
import { subscribeDOM } from "dom-pubsub";

import { V } from "./V";

export const App = () => {
    useEffect(() => {
        subscribeDOM('YO', payload => {
            if (payload.from !== 'REACT') {
                console.log(`REACT: получил от ${payload.from}`);
            }
        })
    }, [])

    return (
        <V/>
    );
}

// packages/svelte/src/components/App.svelte
<script>
    import { onMount } from 'svelte';
    import { publishDOM, subscribeDOM } from 'dom-pubsub';

    onMount(() => {
        subscribeDOM('YO', payload => {
            if (payload.from !== 'SVELTE') {
                console.log(`SVELTE: получил от ${payload.from}`);
            }
        })
    })

    const onclick = () => {
        console.log('SVELTE: отправил');
        publishDOM('YO', {
            from: 'SVELTE'
        })
    }
</script>

<span on:click={onclick}>Б</span>
